const SUBMIT_DATA = 'SUBMIT_DATA'
const SUBMIT_NAME_DATA = 'SUBMIT_NAME_DATA'
const SUBMIT_AGE_DATA = 'SUBMIT_AGE_DATA'
const CLEAR_INPUT = 'CLEAR_INPUT'



export const actionTypes = {
    SUBMIT_DATA,
    SUBMIT_NAME_DATA,
    SUBMIT_AGE_DATA,
    CLEAR_INPUT
}